In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

define global constant

In [2]:
total_len = 10000
scenarios = 10

generate array function

In [3]:
def generate_array(len,sces):
    arr = np.random.random((len,1))
    arr = np.floor(arr*scenarios)
    #print arr
    return arr

In [4]:
arr1 = generate_array(total_len,scenarios);
arr2 = generate_array(total_len,scenarios);
arr3 = 0.5*arr1+0.5*arr2
arr0 = np.append(arr1,arr3)
arr0 = arr0.reshape((2,total_len))
arr0.shape

(2, 10000)

In [5]:
print np.corrcoef(arr1.T,arr2.T)
print np.corrcoef(arr1.T,arr3.T)

[[  1.00000000e+00   3.12221930e-04]
 [  3.12221930e-04   1.00000000e+00]]
[[ 1.          0.70653216]
 [ 0.70653216  1.        ]]


In [6]:
arr1

array([[ 8.],
       [ 1.],
       [ 6.],
       ..., 
       [ 7.],
       [ 6.],
       [ 2.]])

In [7]:
arr2

array([[ 4.],
       [ 2.],
       [ 3.],
       ..., 
       [ 3.],
       [ 4.],
       [ 1.]])

In [8]:
arr3

array([[ 6. ],
       [ 1.5],
       [ 4.5],
       ..., 
       [ 5. ],
       [ 5. ],
       [ 1.5]])

In [9]:
arr0

array([[ 8. ,  1. ,  6. , ...,  7. ,  6. ,  2. ],
       [ 6. ,  1.5,  4.5, ...,  5. ,  5. ,  1.5]])

In [10]:
DataFrame(arr0.T).to_csv('./input_arr_correlated.csv')