# Discrete_entropy, two dimensional array

Author: Heng Shi

This is discrete entropy assessment to see what in 2 factor system, how correlated sources affect the finally entropy.

### import libs

In [1]:
import numpy as np
import matplotlib as mp
import pandas as pd
from pandas import Series, DataFrame
import csv
import math

### define factors

In [2]:
input_name = './input_arr.csv'
df = pd.read_csv(input_name)
ds = np.array(df)

In [3]:
arr1 = ds[:,1]
arr2 = ds[:,2]
length = arr1.shape[0]
sce = max(arr1)
print sce

4.0


### Proba 1D

In [4]:
prob1d_a = np.zeros((sce+1,1))
prob1d_b = np.zeros((sce+1,1))
for i in range(length):
    prob1d_a[arr1[i]] += 1
    prob1d_b[arr2[i]] += 1
prob1d_a = prob1d_a/100.0
prob1d_b = prob1d_b/100.0

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:4: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:5: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


### prob2d

In [5]:
prob2d = np.zeros((sce+1,sce+1))
for i in range(length):
    prob2d[arr1[i]][arr2[i]] += 1
prob2d = prob2d/100.0
print prob2d
print sum(sum(prob2d))

[[ 0.05  0.04  0.04  0.03  0.05]
 [ 0.03  0.05  0.05  0.04  0.05]
 [ 0.03  0.02  0.04  0.01  0.03]
 [ 0.06  0.07  0.03  0.04  0.03]
 [ 0.02  0.05  0.05  0.04  0.05]]
1.0


/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:3: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  app.launch_new_instance()


### calculate entropy

In [6]:
def cal_ent(mat,dim):
    [sha1,sha2] = mat.shape
    len = sha1*sha2
    tmat = mat.reshape((len,1))
    ent_base = 0.0
    for i in range(len):
        ent_base -= tmat[i]*np.log(tmat[i])
    print ent_base
    return ent_base

In [8]:
# 1d entropy
en_1d_a = cal_ent(prob1d_a,1)
en_1d_b = cal_ent(prob1d_b,1)
en_2d = cal_ent(prob2d,2)
en_1d_a+en_1d_b-en_2d

[ 1.59183434]
[ 1.60224949]
[ 3.159489]


array([ 0.03459483])