# Discrete_entropy, two dimensional array

Author: Heng Shi

This is discrete entropy assessment to see what in 2 factor system, how correlated sources affect the finally entropy.

### import libs

In [1]:
import numpy as np
import matplotlib as mpl
opt = 3
len = 10

### define factors

In [2]:
fac1 = ['3','2','1','2','1','3','1','3','2','2'] # factor 1: 1,2,3
fac2 = ['a','b','c','c','c','a','c','b','a','a'] # factor 2: a,b,c
dic1 = {'1':0, '2':0, '3':0}
dic2 = {'a':0, 'b':0, 'c':0}

### initialize datas

In [3]:
for i in fac1:
    entry = i #'%d' % i
    dic1[entry]+=1
for j in fac2:
    entry = j #'%d' % i
    dic2[entry]+=1

### calculate entropy

In [4]:
def cal_ent(dic,optn):
    p = np.zeros((optn,1))
    i = 0
    for entry in dic:
        p[i] = dic[entry]/10.0
        i += 1
    return cal_en_ar(p,optn)

In [5]:
def cal_en_ar(arr,num):
    entropy_base = 0.0
    for i in range(num):
        entropy_base -= arr[i]*np.log(arr[i])
    return entropy_base

In [6]:
def pmat2(dic1,dic2,optn):
    p1 = np.zeros((optn,1))
    p2 = np.zeros((1,optn))
    i = 0
    for entry in dic1:
        p1[i] = dic1[entry]/10.0
        i+=1
    i = 0
    for entry in dic2:
        p2[0][i] = dic2[entry]/10.0
        i+=1
    
    p_mat = np.zeros((optn,optn))
    for i in range(optn):
        for j in range(optn):
            p_mat[i][j] = p1[i]*p2[0][j]
    return p_mat

In [7]:
ent1 = cal_ent(dic1,opt)
ent2 = cal_ent(dic2,opt)

In [8]:
p_2d = pmat2(dic1,dic2,opt)

In [9]:
p_2d

array([[ 0.12,  0.12,  0.06],
       [ 0.12,  0.12,  0.06],
       [ 0.16,  0.16,  0.08]])

In [10]:
p1d = p_2d.reshape((1,opt*opt))
p1d

array([[ 0.12,  0.12,  0.06,  0.12,  0.12,  0.06,  0.16,  0.16,  0.08]])

In [12]:
ent12 = cal_en_ar(p1d.T,opt*opt)
ent12

array([ 2.14382014])

In [13]:
print ent1+ent2-ent12

[ 0.]
